package com.wipro.fileupload.fileUpload.service;

import com.wipro.fileupload.fileUpload.dao.FileUploadRepository;
import com.wipro.fileupload.entities.FileUpload;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.persistence.EntityNotFoundException;

@Service
public class FileUploadService implements IFileUploadService{

    @Autowired
    FileUploadRepository fileUploadRepository;

    @Override
    public FileUpload getFileUploadById(Long id) throws EntityNotFoundException{
        FileUpload fileUpload = fileUploadRepository.findById(id).get();
        if(fileUpload == null) throw new EntityNotFoundException("FileUpload record not found for the given id " + id);
        return fileUpload;
    }

    @Override
    public FileUpload updateFileUpload(Long id, FileUpload fileUpload) throws EntityNotFoundException{
        FileUpload fileUploadEntity = fileUploadRepository.findById(id).get();
        if(fileUploadEntity == null) throw new EntityNotFoundException("FileUpload record not found for the given id " + fileUpload.getFileUploadId());
        fileUploadEntity.setFileName(fileUpload.getFileName());
        fileUploadEntity.setFileUploadUrl(fileUpload.getFileUploadUrl());
        fileUploadEntity.setContextClientId(fileUpload.getContextClientId());
        fileUploadEntity.setEntityContextId(fileUpload.getEntityContextId());
        fileUploadEntity.setUploadLocationContextId(fileUpload.getUploadLocationContextId());
        fileUploadEntity.setUpdatedBy(fileUpload.getUpdatedBy());
        fileUploadEntity.setUpdatedOn(new java.util.Date());
        fileUploadEntity = fileUploadRepository.save(fileUploadEntity);
        return fileUploadEntity;
    }

    @Override
    public FileUpload addFileUpload(FileUpload fileUpload) throws IllegalAccessException{
        if(fileUpload.getFileUploadId() != null)
            throw new IllegalAccessException("You cannot add a fileUpload with the id, this field is autogenerated!");
        fileUpload.setCreatedOn(new java.util.Date());
        return fileUploadRepository.save(fileUpload);
    }

    @Override
    public void deleteFileUploadById(long fileUploadId) throws EntityNotFoundException{
        fileUploadRepository.deleteById(fileUploadId);
    }

}
